// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeZI1ZH8rLF2YISbs_yCZlGKtwoyfCR7s',
    appId: '1:97854373950:web:9289a765e48c54e4db916f',
    messagingSenderId: '97854373950',
    projectId: 'fooddelivapp-bc8ae',
    authDomain: 'fooddelivapp-bc8ae.firebaseapp.com',
    storageBucket: 'fooddelivapp-bc8ae.firebasestorage.app',
    measurementId: 'G-139JWG36XH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArxTxmDjpmX4wNE_tigXEHOvz3wibagaE',
    appId: '1:97854373950:android:7390cc3cf7e74b6edb916f',
    messagingSenderId: '97854373950',
    projectId: 'fooddelivapp-bc8ae',
    storageBucket: 'fooddelivapp-bc8ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX03pdNT-kHhVFBMs6dIW01lHwa0uihrI',
    appId: '1:97854373950:ios:f57a8f9756a384d4db916f',
    messagingSenderId: '97854373950',
    projectId: 'fooddelivapp-bc8ae',
    storageBucket: 'fooddelivapp-bc8ae.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX03pdNT-kHhVFBMs6dIW01lHwa0uihrI',
    appId: '1:97854373950:ios:f57a8f9756a384d4db916f',
    messagingSenderId: '97854373950',
    projectId: 'fooddelivapp-bc8ae',
    storageBucket: 'fooddelivapp-bc8ae.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeZI1ZH8rLF2YISbs_yCZlGKtwoyfCR7s',
    appId: '1:97854373950:web:5e1fd8cd8c216701db916f',
    messagingSenderId: '97854373950',
    projectId: 'fooddelivapp-bc8ae',
    authDomain: 'fooddelivapp-bc8ae.firebaseapp.com',
    storageBucket: 'fooddelivapp-bc8ae.firebasestorage.app',
    measurementId: 'G-03DYK2MFQN',
  );
}
